version: '3'

services:
  rabbitmq:
    build:
      context: ./Docker/RabbitMQ/Dockerfile
      dockerfile: Dockerfile
    image: rabbitmq:3-management-delay
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-home:/var/lib/rabbitmq





  eventstore:
    image: eventstore/eventstore
    ports:
      - "1113:1113" # TCP (default 1113)
      - "2113:2113" # HTTP (default 2113)
    volumes:
      - eventstore-data:/var/lib/eventstore
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=ALL
      - EVENTSTORE_START_STANDARD_PROJECTIONS=TRUE
    
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
  
  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql
      - postgres-config:/etc/postgresql
      - postgres-logs:/var/log/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  dynamo:
    image: dwmkerr/dynamodb
    command: "-sharedDb"
    hostname: dynamo
    restart: always
    volumes:
      - dynamodb:/data
    ports:
      - "8000:8000"

volumes:
  rabbitmq-home:
    driver: local
  eventstore-data:
    driver: local
  mysql-data:
    driver: local
  postgres-data:
    driver: local
  postgres-config:
    driver: local
  postgres-logs:
    driver: local
  dynamodb:
    driver: local
networks:
  default:
    external:
      name: nat